fix up socklet_t compile bug as posted on http://www.neostats.net/boards/viewtopic.php?t=1363

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1268,13 +1268,16 @@ PACKAGE=OPSB
 MODULE_MAJOR=2
 MODULE_MINOR=1
 VERSION=$MODULE_MAJOR.$MODULE_MINOR
+
 cat >>confdefs.h <<_ACEOF
 #define MODULE_VERSION "$VERSION"
 _ACEOF
 
+
 cat >>confdefs.h <<_ACEOF
 #define MODULE_MAJOR "$MODULE_MAJOR"
 _ACEOF
+
 
 cat >>confdefs.h <<_ACEOF
 #define MODULE_MINOR "$MODULE_MINOR"
@@ -3351,6 +3354,61 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking for socklen_t" >&5
+echo $ECHO_N "checking for socklen_t... $ECHO_C" >&6
+if test "${ac_cv_type_socklen_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/types.h>
+   #include <sys/socket.h>
+int
+main ()
+{
+socklen_t len = 42; return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_socklen_t=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_type_socklen_t=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_socklen_t" >&5
+echo "${ECHO_T}$ac_cv_type_socklen_t" >&6
+  if test $ac_cv_type_socklen_t != yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define socklen_t int
+_ACEOF
+
+  fi
+
 echo "$as_me:$LINENO: checking whether time.h and sys/time.h may both be included" >&5
 echo $ECHO_N "checking whether time.h and sys/time.h may both be included... $ECHO_C" >&6
 if test "${ac_cv_header_time+set}" = set; then
@@ -4335,7 +4393,8 @@ if test "${enable_debug+set}" = set; then
    case "$enableval" in
   yes)
         CFLAGS="$CFLAGS -ggdb"
-	cat >>confdefs.h <<\_ACEOF
+
+cat >>confdefs.h <<\_ACEOF
 #define DEBUG 1
 _ACEOF
 
